---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: influx
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[scalr-server::influxdb]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: mysql
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[scalr-server::mysql]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: proxy
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[scalr-server::proxy]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: proxy1
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[scalr-server::proxy]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: worker
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[scalr-server::worker]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: mysql2
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[scalr-server::mysql_slave]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
